; Wizard Launcher - Inno Setup script
;
; Generated inputs come from installer\version.iss, which tools/build.py
; writes from launcher_core/version.py. Do not hardcode a version here.
;
; Two decisions worth knowing about:
;
; 1. This is a per-user install (PrivilegesRequired=lowest, {localappdata}).
;    A Minecraft launcher has no business asking for administrator rights,
;    and a per-user install means the uninstall is complete rather than
;    leaving data behind in another profile.
;
; 2. Game resources are installed next to the executable, NOT into the
;    player's data folder. The launcher copies them across on first run
;    (launcher_core/bootstrap.py), which means it can also repair them if
;    antivirus quarantines a jar. Earlier versions wrote them straight into
;    {userdocs} - that folder is synced by OneDrive on most machines, and
;    syncing a live Minecraft world is how worlds get corrupted.

#include "version.iss"

#define MyAppExeName "WizardLauncher.exe"
#define MyDataDirName "WizardLauncher"

[Setup]
AppId={{8F3D1C2A-6B4E-4E17-9D5A-1E7C2A9B4F60}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion} - {#MyAppEdition}
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}

; Per-user install: no UAC prompt, no shared state, clean uninstall.
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
; The program goes under Programs\; the player's data goes in
; {localappdata}\WizardLauncher (see launcher_core/paths.py). Keeping them
; apart is what lets the uninstaller remove the program without touching a
; forty-hour castle.
DefaultDirName={localappdata}\Programs\{#MyDataDirName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
DisableDirPage=no
AllowNoIcons=yes

OutputDir=..\build_installer
OutputBaseFilename=WizardLauncher-Windows-Setup-{#MyAppVersion}
; Generated by tools/make_icon.py. Guarded so a checkout that has not run it
; yet still produces a working installer instead of failing to compile.
#if FileExists(AddBackslash(SourcePath) + "app.ico")
SetupIconFile=app.ico
#endif
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName} {#MyAppVersion}

; LZMA2/max: the payload is mostly already-compressed jars, so this buys
; little on them, but it does compress the ~100 MB Flet runtime inside the
; executable meaningfully.
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
MinVersion=10.0

LicenseFile=..\resources\servers\1.16.5\eula.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Shortcuts:"

[Files]
; PyInstaller's onedir output: the exe plus its supporting files, all
; installed together (there is no separate self-extracting runtime cache to
; worry about the way there was with Nuitka's onefile mode).
Source: "..\build_pyinstaller\WizardLauncher\*"; DestDir: "{app}"; \
    Flags: ignoreversion recursesubdirs createallsubdirs

; Bundled game content. Copied into the player's data folder on first run by
; launcher_core/bootstrap.py; kept here so a missing jar can be repaired
; without another download.
Source: "..\resources\*"; DestDir: "{app}\resources"; \
    Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\Uninstall {#MyAppName}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Launch {#MyAppName}"; \
    Flags: nowait postinstall skipifsilent

[Code]
{ The player's world, settings and logs are deliberately NOT removed on
  uninstall - reinstalling to recover a castle you spent forty hours in is
  not a recovery story. Offer it explicitly instead. }
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  DataDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    DataDir := ExpandConstant('{localappdata}\{#MyDataDirName}');
    if DirExists(DataDir) then
    begin
      if MsgBox('Also delete your saved world, progress and downloaded game files?' + #13#10 + #13#10 +
                DataDir + #13#10 + #13#10 +
                'Choose No to keep them - reinstalling later will pick up where you left off.',
                mbConfirmation, MB_YESNO or MB_DEFBUTTON2) = IDYES then
        DelTree(DataDir, True, True, True);
    end;
  end;
end;
